### ISSUE TITLE
Compiling with GPU

### ISSUE THREAD

**Issue by sonalgupta** [clab/rnng#10]
Can you add instructions on how to compile/run the library with GPUs?

**Comment by sonalgupta** [comment]
I managed to compile the code with CUDA but the code doesn't run on the GPU: 

```terminate called after throwing an instance of 'std::runtime_error'
  what():  RestrictedLogSoftmax not yet implemented for CUDA
Aborted (core dumped)
```

Is there a way to get the code running on GPU?

**Comment by adhigunasurya** [comment]
Unfortunately at the moment we do not support running on GPU yet due to dependencies on CNN. This might change once we change the dependencies from CNN to the most recent version of DyNet, where most of the operations are implemented on GPU and with autobatching support as well.

**Comment by sonalgupta** [comment]
@adhigunasurya great! Is there a timeline for this change? thanks.

**Comment by adhigunasurya** [comment]
We are currently working on this. This may take some time, since there are some non-trivial changes, such as the fact that class-factored softmax is currently not yet supported by DyNet autobatching. Hopefully within the next month or two.
