### ISSUE TITLE
How to fix "Assertion `end > start' failed"?

### ISSUE THREAD

**Issue by quy-nt** [clab/rnng#6]
Dear authors,

I am training RNNG on Vietnamese treebank. The decoding with discriminative model worked well. However, I met the problem of evaluating joint likelihood under generative model as shown in the attached file:
![decoding with rnng-g - error](https://cloud.githubusercontent.com/assets/17467540/24551813/f4c44738-165e-11e7-9b19-0d693b3cd2c6.png)

Could you please let me know how I can solve it? 

Best regards,
Quy

**Comment by adhigunasurya** [comment]
Hi,

Sorry to hear that, kindly let us know if the issue persists.
