### ISSUE TITLE
Is there trained model that we could play with?

### ISSUE THREAD

**Issue by askerlee** [clab/rnng#8]
Thank you for your great work. As the training process is a bit complex and takes a few days, I wonder is there trained model that we could play with? Thank you very much.

BTW it would be great if someone ports the C++ implementation to Python... :-)

**Comment by adhigunasurya** [comment]
Yes this is a good point. Unfortunately the parameter loading/saving process is specific to the Boost version. Our pretrained model was saved using boost-1.60.0 so any process that loads the pretrained model would need to use the exact same Boost version. I will get back to this and upload a pretrained generative model.

**Comment by adhigunasurya** [comment]
Uploaded the generative pretrained model, link in the README. Let us know if there are further issues.
